version: 2
updates:

  # Maintain dependencies for GitHub Actions Automatically
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Dependencies:"
