name: CI-Build

env:
  # Turn on msvc analysis during build, enable once warnings are clean.
  # DETOURS_ANALYZE: true

  # Compile in parallel where possible.
  CL: /MP

# Triggers the workflow on push or pull request events for the master branch.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        # ARM/ARM64 don't build/link, omit [amd64_arm, amd64_arm64] for now..
        arch: [x64, x86]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head of the pull request.
          # Only include this option if you are running this workflow on pull requests.
          fetch-depth: 2

      # If this run was triggered by a pull request event then checkout
      # the head of the pull request instead of the merge commit.
      # Only include this step if you are running this workflow on pull requests.
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}

      # Setup build environment variables using vcvarsall.bat.
      - name: Configure MSCV Compiler
        uses: ilammy/msvc-dev-cmd@v1.3.0
        with:
          arch: ${{ matrix.arch }}

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: cpp

      # Actually run the build
      - name: Build ${{ matrix.arch }}
        run: nmake

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
